#!/usr/bin/env python3
"""Convert qy-Ads-Rule black.txt into native rule-set formats.

The converter intentionally avoids widening path-, modifier-, or port-specific
ABP rules when a target format cannot represent them safely. Such entries are
written to rules/unsupported.txt instead of being over-blocked.
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
import urllib.request
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

UPSTREAM = "https://raw.githubusercontent.com/rssvcn/qy-Ads-Rule/main/black.txt"
ROOT = Path(__file__).resolve().parents[1]
RULES = ROOT / "rules"
UPSTREAM_DIR = ROOT / "upstream"
META = ROOT / "metadata.json"

HOST_RE = re.compile(r"^[a-z0-9._*?-]+$", re.I)


def fetch_upstream() -> str:
    req = urllib.request.Request(UPSTREAM, headers={"User-Agent": "Adversiting-rule-sync/1.0"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8-sig")


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def wildcard_regex(pattern: str) -> str:
    escaped = re.escape(pattern)
    escaped = escaped.replace(r"\*", ".*").replace(r"\?", ".")
    return f"^{escaped}$"


def loon_url_regex(pattern: str) -> str:
    """Approximate an ABP host wildcard for Loon HTTP(S) URL matching.

    Loon has no domain-level wildcard/regex rule type. URL-REGEX is therefore
    used only as an HTTP(S)-level compensation and is documented as such.
    """
    escaped = re.escape(pattern)
    escaped = escaped.replace(r"\*", ".*").replace(r"\?", ".")
    return rf"^https?://(?:[^/]*\.)?{escaped}(?::\d+)?(?:[/#?]|$)"


def parse(text: str):
    suffixes: set[str] = set()
    keywords: set[str] = set()
    wildcards: set[str] = set()
    ports: dict[str, set[str]] = defaultdict(set)
    unsupported: list[tuple[str, str]] = []
    headers: dict[str, str] = {}

    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("!"):
            m = re.match(r"!\s*([^:]+):\s*(.+)$", line)
            if m:
                headers[m.group(1).strip().lower()] = m.group(2).strip()
            continue
        if line.startswith("#"):
            continue
        if line.startswith("@@"):
            unsupported.append((line, "ABP exception rule is not emitted into a blocking ruleset"))
            continue
        if not line.startswith("||"):
            unsupported.append((line, "unsupported ABP rule type"))
            continue

        core, sep, modifiers = line.partition("$")
        if sep:
            unsupported.append((line, f"ABP modifier not safely portable: ${modifiers}"))
            continue

        body = core[2:]
        if body.endswith("^"):
            body = body[:-1]

        if "/" in body:
            unsupported.append((line, "URL/path-specific ABP rule cannot be represented safely by all routing clients"))
            continue

        host = body
        port = None
        if ":" in host:
            candidate, maybe_port = host.rsplit(":", 1)
            if maybe_port.isdigit() and 1 <= int(maybe_port) <= 65535:
                host, port = candidate, maybe_port
            else:
                unsupported.append((line, "non-standard host/port expression"))
                continue

        host = host.lower().rstrip(".")
        if not host or not HOST_RE.fullmatch(host):
            unsupported.append((line, "invalid or unsupported hostname pattern"))
            continue

        kind: str
        value: str
        if "*" not in host and "?" not in host:
            kind, value = "suffix", host
        elif host.startswith("*.") and "*" not in host[2:] and "?" not in host[2:]:
            kind, value = "suffix", host[2:]
        elif re.fullmatch(r"\*[a-z0-9_-]+\*", host, re.I):
            kind, value = "keyword", host.strip("*")
        else:
            kind, value = "wildcard", host

        if port:
            if kind == "suffix":
                ports[port].add(value)
            else:
                unsupported.append((line, "wildcard/keyword combined with destination port is not portable"))
            continue

        if kind == "suffix":
            suffixes.add(value)
        elif kind == "keyword":
            keywords.add(value)
        else:
            wildcards.add(value)

    return headers, sorted(suffixes), sorted(keywords), sorted(wildcards), ports, unsupported


def header_lines(prefix: str, headers: dict[str, str], source_hash: str) -> list[str]:
    title = headers.get("title", "晴雅广告拦截规则")
    version = headers.get("version", "unknown")
    return [
        f"{prefix} Title: {title}",
        f"{prefix} Upstream-Version: {version}",
        f"{prefix} Source: {UPSTREAM}",
        f"{prefix} Source-SHA256: {source_hash}",
        f"{prefix} Generated by scripts/convert_rules.py",
        "",
    ]


def write_text(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def build_outputs(headers, suffixes, keywords, wildcards, ports, unsupported, source_hash):
    RULES.mkdir(parents=True, exist_ok=True)
    UPSTREAM_DIR.mkdir(parents=True, exist_ok=True)

    # Loon: domain wildcard/regex rules do not exist. Preserve exact domain
    # rules, express port constraints with native logical AND, and compensate
    # host wildcards at the HTTP(S) layer with URL-REGEX.
    loon = header_lines("#", headers, source_hash)
    loon += [
        "# Wildcard note: Loon has no domain-level wildcard rule.",
        "# The URL-REGEX entries below compensate these rules for HTTP/HTTPS only.",
        "",
    ]
    loon += [f"DOMAIN-SUFFIX,{d}" for d in suffixes]
    loon += [f"DOMAIN-KEYWORD,{k}" for k in keywords]
    loon += [f"URL-REGEX,{loon_url_regex(w)}" for w in wildcards]
    for port in sorted(ports, key=int):
        loon += [f"AND,((DOMAIN-SUFFIX,{d}),(DEST-PORT,{port}))" for d in sorted(ports[port])]
    write_text(RULES / "Loon.list", "\n".join(loon))

    # Surge external RULE-SET syntax. DOMAIN-WILDCARD and logical AND are
    # documented native rule forms.
    surge = header_lines("#", headers, source_hash)
    surge += [f"DOMAIN-SUFFIX,{d}" for d in suffixes]
    surge += [f"DOMAIN-KEYWORD,{k}" for k in keywords]
    surge += [f"DOMAIN-WILDCARD,{w}" for w in wildcards]
    for port in sorted(ports, key=int):
        surge += [f"AND,((DOMAIN-SUFFIX,{d}),(DEST-PORT,{port}))" for d in sorted(ports[port])]
    write_text(RULES / "Surge.list", "\n".join(surge))

    # Quantumult X remote filter syntax from the official sample.
    quanx = header_lines("#", headers, source_hash)
    quanx += [f"host-suffix, {d}, reject" for d in suffixes]
    quanx += [f"host-keyword, {k}, reject" for k in keywords]
    quanx += [f"host-wildcard, {w}, reject" for w in wildcards]
    write_text(RULES / "QuanX.list", "\n".join(quanx))

    # Mihomo (modern Clash.Meta) classical rule-provider format.
    # DOMAIN-WILDCARD, DST-PORT and logical AND are native Mihomo rules.
    clash_payload = [f"DOMAIN-SUFFIX,{d}" for d in suffixes]
    clash_payload += [f"DOMAIN-KEYWORD,{k}" for k in keywords]
    clash_payload += [f"DOMAIN-WILDCARD,{w}" for w in wildcards]
    for port in sorted(ports, key=int):
        clash_payload += [
            f"AND,((DOMAIN-SUFFIX,{d}),(DST-PORT,{port}))"
            for d in sorted(ports[port])
        ]
    clash = [
        "# Mihomo / Clash.Meta classical rule-provider",
        "# Requires modern Mihomo rule syntax; legacy Dreamacro Clash is not targeted.",
        f"# Source: {UPSTREAM}",
        "payload:",
    ]
    clash += ["  - " + json.dumps(item, ensure_ascii=False) for item in clash_payload]
    write_text(RULES / "Clash.yaml", "\n".join(clash))

    # sing-box source rule-set. Domain match fields in one headless rule are OR'ed.
    sb_rule: dict[str, object] = {}
    if suffixes:
        sb_rule["domain_suffix"] = suffixes
    if keywords:
        sb_rule["domain_keyword"] = keywords
    if wildcards:
        sb_rule["domain_regex"] = [wildcard_regex(w) for w in wildcards]
    sb_rules: list[dict[str, object]] = [sb_rule] if sb_rule else []
    for port in sorted(ports, key=int):
        sb_rules.append({"domain_suffix": sorted(ports[port]), "port": [int(port)]})
    singbox = {"version": 3, "rules": sb_rules}
    write_text(RULES / "SingBox.json", json.dumps(singbox, ensure_ascii=False, indent=2))

    # Xray routing snippet. `block` must correspond to a blackhole outbound tag.
    xray_domains = [f"domain:{d}" for d in suffixes]
    xray_domains += [f"keyword:{k}" for k in keywords]
    xray_domains += [f"regexp:{wildcard_regex(w)}" for w in wildcards]
    xray_rules: list[dict[str, object]] = []
    if xray_domains:
        xray_rules.append({"domain": xray_domains, "outboundTag": "block"})
    for port in sorted(ports, key=int):
        xray_rules.append({
            "domain": [f"domain:{d}" for d in sorted(ports[port])],
            "port": int(port),
            "outboundTag": "block",
        })
    xray = {"routing": {"domainStrategy": "AsIs", "rules": xray_rules}}
    write_text(RULES / "Xray.json", json.dumps(xray, ensure_ascii=False, indent=2))

    unsupported_lines = header_lines("#", headers, source_hash)
    unsupported_lines += ["# These entries were intentionally not widened into domain blocks.", ""]
    for raw, reason in unsupported:
        unsupported_lines += [f"# {reason}", raw, ""]
    write_text(RULES / "unsupported.txt", "\n".join(unsupported_lines))


def main() -> int:
    text = fetch_upstream()
    source_hash = sha256_text(text)
    converter_hash = sha256_text(Path(__file__).read_text(encoding="utf-8"))

    previous = {}
    if META.exists():
        try:
            previous = json.loads(META.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            previous = {}

    if previous.get("source_sha256") == source_hash and previous.get("converter_sha256") == converter_hash:
        print("No upstream or converter change; nothing to update.")
        return 0

    headers, suffixes, keywords, wildcards, ports, unsupported = parse(text)
    write_text(UPSTREAM_DIR / "black.txt", text)
    build_outputs(headers, suffixes, keywords, wildcards, ports, unsupported, source_hash)

    meta = {
        "source": UPSTREAM,
        "upstream_title": headers.get("title"),
        "upstream_version": headers.get("version"),
        "source_sha256": source_hash,
        "converter_sha256": converter_hash,
        "last_sync_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "counts": {
            "domain_suffix": len(suffixes),
            "domain_keyword": len(keywords),
            "domain_wildcard": len(wildcards),
            "port_specific": sum(len(v) for v in ports.values()),
            "unsupported": len(unsupported),
        },
        "coverage": {
            "surge_portable_exact": len(suffixes) + len(keywords) + len(wildcards) + sum(len(v) for v in ports.values()),
            "mihomo_portable_exact": len(suffixes) + len(keywords) + len(wildcards) + sum(len(v) for v in ports.values()),
            "singbox_portable_exact": len(suffixes) + len(keywords) + len(wildcards) + sum(len(v) for v in ports.values()),
            "xray_portable_exact": len(suffixes) + len(keywords) + len(wildcards) + sum(len(v) for v in ports.values()),
            "loon_domain_exact": len(suffixes) + len(keywords) + sum(len(v) for v in ports.values()),
            "loon_http_compensated_wildcards": len(wildcards),
            "quanx_without_port": len(suffixes) + len(keywords) + len(wildcards),
        },
    }
    write_text(META, json.dumps(meta, ensure_ascii=False, indent=2))
    print(json.dumps(meta, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
